services:
  app:
    build: .
    container_name: dental_reviews_backend
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://darkness:darkness3729@database:5432/dental
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - images_data:/app/images
    restart: unless-stopped

  database:
    image: postgres:16
    container_name: dental_reviews_database
    environment:
      POSTGRES_USER: darkness
      POSTGRES_PASSWORD: darkness3729
      POSTGRES_DB: dental
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  images_data:
  postgres_data:
